"""Phase 5.4 Opportunity Model

Revision ID: 738c068c7ca4
Revises: 76814dd6a086
Create Date: 2026-09-11 03:55:50.673447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '738c068c7ca4'
down_revision: Union[str, None] = '76814dd6a086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opportunities')
    op.create_table('opportunities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('distributor_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('location_id', sa.String(), nullable=True),
    sa.Column('demand_score', sa.Float(), nullable=True),
    sa.Column('supply_score', sa.Float(), nullable=True),
    sa.Column('competition_score', sa.Float(), nullable=True),
    sa.Column('opportunity_score', sa.Float(), nullable=True),
    sa.Column('potential_retailer_count', sa.Integer(), nullable=True),
    sa.Column('recommended_initial_stock', sa.Integer(), nullable=True),
    sa.Column('distributor_fit', sa.String(), nullable=True),
    sa.Column('evidence_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributor_profiles.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_distributor_id'), 'opportunities', ['distributor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'opportunities', type_='foreignkey')
    op.drop_index(op.f('ix_opportunities_distributor_id'), table_name='opportunities')
    op.drop_column('opportunities', 'evidence_json')
    op.drop_column('opportunities', 'distributor_fit')
    op.drop_column('opportunities', 'distributor_id')
    # ### end Alembic commands ###
