"""Hardening Phase 5.3A constraints

Revision ID: 76814dd6a086
Revises: 0a5eec91cbfa
Create Date: 2026-09-11 03:41:34.543731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76814dd6a086'
down_revision: Union[str, None] = '0a5eec91cbfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supply_gaps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('location_id', sa.String(), nullable=True),
    sa.Column('retailer_demand_count', sa.Integer(), nullable=True),
    sa.Column('supplier_count', sa.Integer(), nullable=True),
    sa.Column('available_supplier_count', sa.Integer(), nullable=True),
    sa.Column('low_stock_supplier_count', sa.Integer(), nullable=True),
    sa.Column('out_of_stock_supplier_count', sa.Integer(), nullable=True),
    sa.Column('gap_score', sa.Float(), nullable=True),
    sa.Column('supply_level', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supply_gaps_category_id'), 'supply_gaps', ['category_id'], unique=False)
    op.create_index(op.f('ix_supply_gaps_location_id'), 'supply_gaps', ['location_id'], unique=False)
    op.create_index(op.f('ix_supply_gaps_product_id'), 'supply_gaps', ['product_id'], unique=False)
    op.add_column('demand_signals', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demand_signals', 'updated_at')
    op.drop_index(op.f('ix_supply_gaps_product_id'), table_name='supply_gaps')
    op.drop_index(op.f('ix_supply_gaps_location_id'), table_name='supply_gaps')
    op.drop_index(op.f('ix_supply_gaps_category_id'), table_name='supply_gaps')
    op.drop_table('supply_gaps')
    # ### end Alembic commands ###
