"""shop inventory, storefront and loan applications

Revision ID: adfbe48d1dcd
Revises: b2e4d81a6f37
Create Date: 2026-09-13 03:17:10.298716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adfbe48d1dcd'
down_revision: Union[str, None] = 'b2e4d81a6f37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('location_id', sa.String(), nullable=True),
    sa.Column('address_line', sa.String(), nullable=True),
    sa.Column('landmark', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('loan_applications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('scheme_id', sa.String(), nullable=False),
    sa.Column('scheme_name', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('tenure_months', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('matched_criteria', sa.Text(), nullable=True),
    sa.Column('lender_reference', sa.String(), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount > 0', name='check_loan_amount_positive'),
    sa.CheckConstraint('tenure_months > 0', name='check_loan_tenure_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_applications_reference'), 'loan_applications', ['reference'], unique=True)
    op.create_index(op.f('ix_loan_applications_scheme_id'), 'loan_applications', ['scheme_id'], unique=False)
    op.create_index(op.f('ix_loan_applications_status'), 'loan_applications', ['status'], unique=False)
    op.create_index(op.f('ix_loan_applications_user_id'), 'loan_applications', ['user_id'], unique=False)
    op.create_table('delivery_runners',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('retailer_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('mobile', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_runners_retailer_id'), 'delivery_runners', ['retailer_id'], unique=False)
    op.create_table('consumer_orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('order_number', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('retailer_id', sa.String(), nullable=False),
    sa.Column('runner_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('delivery_fee', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('delivery_address', sa.String(), nullable=True),
    sa.Column('delivery_landmark', sa.String(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('customer_note', sa.Text(), nullable=True),
    sa.Column('placed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.CheckConstraint('total >= 0', name='check_consumer_order_total'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.id'], ),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailer_profiles.id'], ),
    sa.ForeignKeyConstraint(['runner_id'], ['delivery_runners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_consumer_order_shop_status', 'consumer_orders', ['retailer_id', 'status'], unique=False)
    op.create_index(op.f('ix_consumer_orders_customer_id'), 'consumer_orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_consumer_orders_order_number'), 'consumer_orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_consumer_orders_retailer_id'), 'consumer_orders', ['retailer_id'], unique=False)
    op.create_index(op.f('ix_consumer_orders_status'), 'consumer_orders', ['status'], unique=False)
    op.create_table('retailer_inventory',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('retailer_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('product_variant_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.Column('selling_price', sa.Float(), nullable=True),
    sa.Column('reorder_level', sa.Integer(), nullable=False),
    sa.Column('shelf_life_days', sa.Integer(), nullable=True),
    sa.Column('is_listed_online', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('quantity >= 0', name='check_retailer_inventory_quantity'),
    sa.CheckConstraint('reorder_level >= 0', name='check_retailer_reorder_level'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('retailer_id', 'product_variant_id', name='uq_retailer_variant')
    )
    op.create_index(op.f('ix_retailer_inventory_is_listed_online'), 'retailer_inventory', ['is_listed_online'], unique=False)
    op.create_index(op.f('ix_retailer_inventory_product_id'), 'retailer_inventory', ['product_id'], unique=False)
    op.create_index(op.f('ix_retailer_inventory_product_variant_id'), 'retailer_inventory', ['product_variant_id'], unique=False)
    op.create_index(op.f('ix_retailer_inventory_retailer_id'), 'retailer_inventory', ['retailer_id'], unique=False)
    op.create_index('ix_retailer_inventory_shop_listed', 'retailer_inventory', ['retailer_id', 'is_listed_online'], unique=False)
    op.create_table('consumer_order_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('inventory_id', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('variant_name', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('line_total', sa.Float(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='check_consumer_item_quantity'),
    sa.CheckConstraint('unit_price >= 0', name='check_consumer_item_price'),
    sa.ForeignKeyConstraint(['inventory_id'], ['retailer_inventory.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['consumer_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumer_order_items_order_id'), 'consumer_order_items', ['order_id'], unique=False)
    op.create_table('inventory_batches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('inventory_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.Column('received_on', sa.Date(), nullable=False),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint('quantity >= 0', name='check_batch_quantity_positive'),
    sa.ForeignKeyConstraint(['inventory_id'], ['retailer_inventory.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_batches_expires_on'), 'inventory_batches', ['expires_on'], unique=False)
    op.create_index(op.f('ix_inventory_batches_inventory_id'), 'inventory_batches', ['inventory_id'], unique=False)
    op.create_table('stock_movements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('retailer_id', sa.String(), nullable=False),
    sa.Column('inventory_id', sa.String(), nullable=False),
    sa.Column('quantity_delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint('quantity_delta != 0', name='check_movement_nonzero'),
    sa.ForeignKeyConstraint(['inventory_id'], ['retailer_inventory.id'], ),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stock_movement_shop_time', 'stock_movements', ['retailer_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_stock_movements_created_at'), 'stock_movements', ['created_at'], unique=False)
    op.create_index(op.f('ix_stock_movements_inventory_id'), 'stock_movements', ['inventory_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_reason'), 'stock_movements', ['reason'], unique=False)
    op.create_index(op.f('ix_stock_movements_reference_id'), 'stock_movements', ['reference_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_retailer_id'), 'stock_movements', ['retailer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_movements_retailer_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_reference_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_reason'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_inventory_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_created_at'), table_name='stock_movements')
    op.drop_index('ix_stock_movement_shop_time', table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_inventory_batches_inventory_id'), table_name='inventory_batches')
    op.drop_index(op.f('ix_inventory_batches_expires_on'), table_name='inventory_batches')
    op.drop_table('inventory_batches')
    op.drop_index(op.f('ix_consumer_order_items_order_id'), table_name='consumer_order_items')
    op.drop_table('consumer_order_items')
    op.drop_index('ix_retailer_inventory_shop_listed', table_name='retailer_inventory')
    op.drop_index(op.f('ix_retailer_inventory_retailer_id'), table_name='retailer_inventory')
    op.drop_index(op.f('ix_retailer_inventory_product_variant_id'), table_name='retailer_inventory')
    op.drop_index(op.f('ix_retailer_inventory_product_id'), table_name='retailer_inventory')
    op.drop_index(op.f('ix_retailer_inventory_is_listed_online'), table_name='retailer_inventory')
    op.drop_table('retailer_inventory')
    op.drop_index(op.f('ix_consumer_orders_status'), table_name='consumer_orders')
    op.drop_index(op.f('ix_consumer_orders_retailer_id'), table_name='consumer_orders')
    op.drop_index(op.f('ix_consumer_orders_order_number'), table_name='consumer_orders')
    op.drop_index(op.f('ix_consumer_orders_customer_id'), table_name='consumer_orders')
    op.drop_index('ix_consumer_order_shop_status', table_name='consumer_orders')
    op.drop_table('consumer_orders')
    op.drop_index(op.f('ix_delivery_runners_retailer_id'), table_name='delivery_runners')
    op.drop_table('delivery_runners')
    op.drop_index(op.f('ix_loan_applications_user_id'), table_name='loan_applications')
    op.drop_index(op.f('ix_loan_applications_status'), table_name='loan_applications')
    op.drop_index(op.f('ix_loan_applications_scheme_id'), table_name='loan_applications')
    op.drop_index(op.f('ix_loan_applications_reference'), table_name='loan_applications')
    op.drop_table('loan_applications')
    op.drop_table('customer_profiles')
    # ### end Alembic commands ###
